#release configuration
#Fri Jan 17 11:45:12 IST 2025
project.scm.edu.cornell.weill.reciter\:reciter-article-model.url=https\://github.com/wcmc-its/ReCiter-Article-Model
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.tag=reciter-article-model-2.0.32
pushChanges=false
scm.url=scm\:git\:git@github.com\:wcmc-its/ReCiter-Article-Model.git
preparationGoals=clean verify
project.rel.edu.cornell.weill.reciter\:reciter-article-model=2.0.32
project.scm.edu.cornell.weill.reciter\:reciter-article-model.connection=scm\:git\:git\://github.com/wcmc-its/ReCiter-Article-Model.git
project.scm.edu.cornell.weill.reciter\:reciter-article-model.developerConnection=scm\:git\:git@github.com\:wcmc-its/ReCiter-Article-Model.git
remoteTagging=true
projectVersionPolicyId=default
scm.commentPrefix=[maven-release-plugin] 
project.dev.edu.cornell.weill.reciter\:reciter-article-model=2.0.33-SNAPSHOT
exec.snapshotReleasePluginAllowed=false
exec.additionalArguments=-Dgpg.passphrase\=${env.GPG_PASSPHRASE}
completedPhase=end-release
project.scm.edu.cornell.weill.reciter\:reciter-article-model.tag=reciter-article-model-2.0.18
